#! /bin/csh -f
set INCLUDE = /home/jvh640/CS2123/ANDERSON_Recitation07/booklib
set CSLIB = $INCLUDE/cslib.a
set LIBRARIES = ($CSLIB -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
